allow for automated overlay installation

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,51 +1,85 @@
 #!/usr/bin/env bash
 
-CWD=$(cd -- $(dirname $0) && pwd)
-
-if [ -r /etc/os-release ]
-then
-    DISTRO=$(awk -F= '/^ID=/ {print $2}' /etc/os-release | xargs)
-else
-    DISTRO=unknown
-fi
-
-for CMD in doas sudo
-do
-    if (command -v $CMD 2>&1 > /dev/null)
-    then
-        SU=$CMD
-    fi
-done
-
 function log
 {
     local LVL=$1
     local MSG=$2
 
-    case $1 in
-        info) printf "\x1b[1;34m:: \x1b[39m$MSG\x1b[0m\n"  >&2 ;;
-        warn) printf "\x1b[1;33m:: \x1b[39m$MSG\x1b[0m\n"  >&2 ;;
-        err)  printf "\x1b[1;31m:: \x1b[39m$MSG\x1b[0m\n"  >&2 ;;
-        ask)  printf "\x1b[1;37m:: \x1b[39m$MSG\x1b[0m"    >&2 ;;
-        *)    printf "$MSG\n"                              >&2 ;;
+    case $LVL in
+        info) printf "\x1b[0;34m:: \x1b[39m$MSG\x1b[0m\n" >&2 ;;
+        warn) printf "\x1b[1;33m:: \x1b[39m$MSG\x1b[0m\n" >&2 ;;
+        err)  printf "\x1b[1;31m:: \x1b[39m$MSG\x1b[0m\n" >&2 ;;
+        *)    printf "$MSG\n"                             >&2 ;;
     esac
 }
 
-function checkoverlay
+function askyesno
 {
-    if !(eselect repository list -i 2>&1 | grep --quiet "] $1")
-    then
-        log warn "The $1 overlay is not enabled!"
-        log warn "To enable it, run:"
-        log warn "  $SU eselect repository enable $1"
-        log warn "  $SU emaint sync -r $1"
-        echo
-        return 1
-    fi
+    local MSG=$1
 
-    return 0
+    printf "\x1b[1;32m?? \x1b[39m$MSG\x1b[0m " >&2
+    read ANS && [ -z "$ANS" ] || [ "$ANS" == "y" ] || [ "$ANS" == "Y" ]
 }
 
+function run
+{
+    $@ >&2
+}
+
+function defaultsu
+{
+    su -c "$*"
+}
+
+CWD=$(cd -- $(dirname $0) && pwd)
+
+# Get the distro
+[ -r /etc/os-release ] && DISTRO=$(awk -F= '/^ID=/ {print $2}' /etc/os-release | xargs)
+
+# Get the package manager if the distro is supported
+case $DISTRO in
+    arch)
+        PMCMD="pacman --needed --sync"
+        ;;
+    gentoo)
+        PMCMD="emerge --noreplace --ask --verbose"
+        ;;
+esac
+
+# Get the command that will be used to run as root (fallback to su)
+SUCMD=defaultsu
+for CMD in doas sudo
+do
+    (command -v $CMD 2>&1 > /dev/null) && SUCMD=$CMD && break
+done
+
+# Check if a Gentoo overlay is enabled. Prompt user to enable it if it isn't.
+function checkoverlay
+{
+    local OVERLAY=$1
+
+    # Check if the overlay is enabled
+    eselect repository list -i 2>&1 | grep --quiet "] $OVERLAY" && return 0
+
+    log warn "The '$OVERLAY' overlay is required to install requested packages."
+    askyesno "Would you like to enable it? [Y/n]" || return 1
+
+    # Make sure the 'repository' eselect module is enabled
+    if !(eselect modules list 2>&1 | grep --quiet "^  repository")
+    then
+        log warn "The 'repository' eselect module is not installed."
+
+        askyesno "Would you like to install it? [Y/n]"                      &&
+            run $SUCMD emerge --ask --verbose app-select/eselect-repository ||
+            return 1
+    fi
+
+    # Enable and sync the requested overlay
+    run $SUCMD eselect repository enable $OVERLAY || return 1
+    run $SUCMD emaint sync -r $OVERLAY            || return 1
+}
+
+# Get the packages required by a given program for the distro.
 function getpkgs
 {
     local PROG=$1
@@ -81,44 +115,25 @@ function getpkgs
         fonts@gentoo)
             echo media-fonts/{jetbrains-mono,symbols-nerd-font,noto}
             ;;
-        extras@arch)
+        shextras@arch)
             echo lsd ripgrep fd bat
             ;;
-        extras@gentoo)
+        shextras@gentoo)
             echo sys-apps/{lsd,ripgrep,fd,bat}
             ;;
         *)
-            log warn "No package preset for program '$PROG' on $DISTRO"
+            log warn "No package preset for program '$PROG'."
             ;;
     esac
 }
 
-function installpkgs
-{
-    local PKGS=$@
-
-    case $DISTRO in
-        arch)
-            $SU pacman --needed --sync $PKGS
-            ;;
-        gentoo)
-            $SU emerge --noreplace --ask --verbose $PKGS
-            ;;
-        *)
-            log err "Cannot install packages. ($DISTRO is not supported)"
-            ;;
-    esac
-}
-
+# Install the requested programs.
 function installprogs
 {
-    if [ "$DISTRO" = "gentoo" ] && !(eselect modules list 2>&1 | grep --quiet '^  redpository')
+    if [ -z "$PMCMD" ]
     then
-        log warn "The eselect 'repository' module is not installed."
-        log warn "It might be needed to enable overlays for certain packages."
-        log warn "Run '$SU emerge --ask --verbose app-select/eselect-repository' to install it."
-        log info "Continuing..."
-        echo
+        log err "Cannot install packages on $DISTRO."
+        return 1
     fi
 
     for PROG in $@
@@ -126,23 +141,23 @@ function installprogs
         PKGS+="$(getpkgs $PROG) "
     done
 
-    if (echo $PKGS | grep --quiet '\w')
+    if (grep --quiet '\w' <<< $PKGS)
     then
-        log info "The following packages will be installed:"
+        log info "The following packages and their dependencies will be installed:"
         for PKG in $PKGS
         do
             log info "  $PKG"
         done
 
-        echo
         [ "$DISTRO" = "gentoo" ] && log info "Ensure desired USE flags have been set."
-        log ask "Continue? (Control + C to cancel) "
-        read || return 1
 
-        installpkgs $PKGS
+        askyesno "Continue [Y/n]" && $SUCMD $PMCMD $PKGS
+    else
+        log warn "No packages to be installed."
     fi
 }
 
+# Create a symlink for the provided program's config.
 function linkconfig
 {
     local CONF=${XDG_CONFIG_HOME:-$HOME/.config}
@@ -176,13 +191,14 @@ function linkconfig
 
     if ! [ -e $DST ]
     then
-        mkdir --parents --verbose $(dirname $DST)
-        ln --symbolic --verbose $CWD/$SRC $DST
+        run mkdir --parents --verbose $(dirname $DST)
+        run ln --symbolic --verbose $CWD/$SRC $DST
     else
         log warn "Not linking '$1' to '$DST' because a file already exists"
     fi
 }
 
+# Link the provided programs' configs.
 function linkconfigs
 {
     for PROG in $@
@@ -193,7 +209,7 @@ function linkconfigs
 
 function getallprogs
 {
-    echo zsh nvim hypr tmux fonts extras
+    echo zsh nvim hypr tmux fonts shextras
 }
 
 function linkcleanhome
@@ -226,8 +242,8 @@ case $1 in
         linkcleanhome
         ;;
     everything)
-        $CWD/setup install all
-        $CWD/setup link all
-        $CWD/setup keepcleanhome
+        $CWD/setup install all       &&
+            $CWD/setup link all      &&
+            $CWD/setup keepcleanhome
         ;;
 esac
